version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: voicechat
      POSTGRES_USER: voicechat_user
      POSTGRES_PASSWORD: voicechat_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voicechat_user -d voicechat"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Voice Chat Application
  voicechat:
    build: .
    environment:
      DATABASE_URL: postgresql://voicechat_user:voicechat_password@postgres:5432/voicechat
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: mistral
      HOST: 0.0.0.0
      PORT: 8000
      DEFAULT_VOICE: en-US-JennyNeural
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./static:/app/static
    restart: unless-stopped

  # Ollama Service (optional - you can use external Ollama)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Uncomment the following lines to automatically pull Mistral model
    # command: >
    #   sh -c "ollama serve &
    #          sleep 10 &&
    #          ollama pull mistral &&
    #          wait"

volumes:
  postgres_data:
  ollama_data: 